[workspace]
resolver = "2"
members = ["rmde-core"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Indrek"]
license = "MIT"

[workspace.dependencies]
ropey = "1.6"
tree-sitter = "0.24"
tree-sitter-md = "0.3"
parking_lot = "0.12"
thiserror = "2.0"
